index:
    path: /
    controller: App\Controller\HomeController::index
reset-password:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::index
app-register:
    path: /app-register
    controller: App\Controller\RegistrationController::register